name: Start BOT

#on: workflow_dispatch

on:
  push:
  workflow_dispatch:
#  schedule:
#    - cron: '*/5 * * * *'


jobs:
  Go-pars:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Run-BOT
        run: sudo docker-compose up


      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ secrets.CI_TOKEN }}
          repository: ${{ 'sapfire65/beehabce_bot' }}
          retain_days: 0
          keep_minimum_runs: 3





